name: Publish Package & Storybook

on:
  push:
    branches:
      - gh-workflow # temp to test

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Latest
        run: yarn build && yarn build-storybook

      - name: Publish NPM Package
        run: echo "yarn publish --non-interactive"

      - name: Update GH Pages
        run: yarn deploy-storybook